### ISSUE TITLE
推送最新文章时如果不足20篇报警告

### ISSUE THREAD

**Issue by brokenpoems** [ethanzhao2001/Sitemap-For-Typecho#3]
报如下警告(已忽略部分路径)
```
Argument 1 passed to Typecho\Router::get() must be of the type string, null given, called in .../usr/plugins/Sitemap/Action.php on line 146
TypeError: Argument 1 passed to Typecho\Router::get() must be of the type string, null given, called in .../usr/plugins/Sitemap/Action.php on line 146 and defined in .../var/Typecho/Router.php:170
Stack trace:
#0 .../usr/plugins/Sitemap/Action.php(146): Typecho\Router::get()
#1 .../usr/plugins/Sitemap/Push.php(56): submit()
#2 .../admin/extending.php(14): require_once('...')
#3 {main}
```

**Comment by ethanzhao2001** [comment]
增加了提醒，避免报错
